name: 'update'

on:
  push

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch
        run: echo {{ BRANCH_NAME }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H ${{ secrets.HOST }}  >> ~/.ssh/known_hosts

      - name: Update
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /root/tools && zsh update_code.sh ${{ BRANCH_NAME }}"
